### ISSUE TITLE
Imported records have empty CharacterString inserted, making them invalid

### ISSUE THREAD

**Issue by nmtoken** [metadata101/iso19139.gemini23#5] opened 2019-11-22 15:04 UTC
Probably related to #4 

Records imported from https://github.com/AGIGemini/Schematron/tree/master/samples into geonet38 which were valid against the GEMINI schematron, become invalid because of insertion of  an empty `<gco:CharacterString/>` element.  

Schematron rule broken is:  **AT-6: Free text elements should not be empty**

Applies to multiple locations:

File `<gco:CharacterString>9df8df51-6332-37a8-e044-0003ba9b0d98</gco:CharacterString>` holds all examples.

### parentIdentifier

    <gmd:parentIdentifier gco:nilReason="inapplicable"/> (valid) 

becomes invalid:

    <gmd:parentIdentifier xmlns:xs="http://www.w3.org/2001/XMLSchema"
                         xmlns:geonet="http://www.fao.org/geonetwork"
                         gco:nilReason="missing">
        <gco:CharacterString/>
    </gmd:parentIdentifier>

Also worth noting that metadata nil reason changes from `inapplicable` to `missing`

### hierarchyLevelName

    <gmd:hierarchyLevelName gco:nilReason="inapplicable"/>  (valid) 

becomes invalid:

      <gmd:hierarchyLevelName xmlns:xs="http://www.w3.org/2001/XMLSchema"
                           xmlns:geonet="http://www.fao.org/geonetwork"
                           gco:nilReason="missing">
            <gco:CharacterString/>
      </gmd:hierarchyLevelName>

### explanation (part of a gmd:report)

    
                     <gmd:explanation gco:nilReason="inapplicable"/> (valid) 

become invalid:

    
              <gmd:explanation gco:nilReason="missing">
                   <gco:CharacterString/>
               </gmd:explanation>

### measureDescription (part of a gmd:report)

    <gmd:measureDescription gco:nilReason="unknown"/> (valid) 

becomes invalid:

    <gmd:measureDescription gco:nilReason="missing">
         <gco:CharacterString/>
     </gmd:measureDescription>

**Comment by archaeogeek** [comment] 2020-02-10 17:42
@nmtoken would you say that you think any element marked as optional in https://www.agi.org.uk/40-gemini/1250-element-summary should be able to handle a `nilreason=inapplicable`?

The position I want to get to is that we display those elements correctly in the editor and obviously leave the record unchanged at the end of import/validation, but also allow people to fill in the element should they wish without needing to go into the xml or the full view in the geonetwork editor.

**Comment by archaeogeek** [comment] 2020-02-11 10:26
@nmtoken I've had a response back from the AGI working group about this, and fundamentally they don't want to see `nilreason=applicable` being used for optional elements. The following is a snippet from the email:

> So it shouldn’t be used on the elements that are optional in the schema, which includes all those listed as “optional” at https://www.agi.org.uk/40-gemini/1250-element-summary. And it shouldn’t be used for the ones listed at 2.2.10 as “not nillable” (which are enforced by the GEMINI Schematron). 

This leaves the following elements as the only ones that should have a `nilreason=inapplicable`:

> 6 Keyword – i.e. the ‘keyword’ element within the MD_Keywords class – I’ve no idea why we allowed that!
> 
> 8 Dataset reference date – the Citation could have a void ‘date’ element, with a reason. 
> 
> 10 Lineage – the Li_Lineage could have a void ‘statement’ element, with a reason 
> 
> 17 Spatial reference system – the RS_Identifier could have a void ‘code’ statement 
> 
> 21 Data format – the MD_Format name & version elements could each (independently) be void – this is mentioned in the GEMINI Guidance 
> 
> 30 Metadata date – the Schematron does allow nilReason, but I’d really suggest not doing this – I don’t know what it would do on harvest! 
> 
> 41 Conformity explanation – the explanation is voidable, with a reason

So for those elements only, we will handle `nilreason=inapplicable` unchanged. I'm going to close the other tickets related to the same problem to avoid duplication but I'll let you know when we have something that hopefully handles this.

**Comment by nmtoken** [comment] 2020-02-11 11:19
> @nmtoken would you say that you think any element marked as optional in https://www.agi.org.uk/40-gemini/1250-element-summary should be able to handle a nilreason=inapplicable?

Strictly. yes, they should be able to handle them.  But handling them and defaulting to them are different things.    They should be able to handle all the nil reasons, unless the guidance says that there is a restriction of types allowed.

For the  `<gmd:descriptiveKeywords>` section `<gmd:keyword></gmd:keyword>` is APISO schema valid, but GEMINI  invalid (that is GEMINI 2.1 to 2.3).

I wouldn't have thought that `nilreason="inapplicable"` is likely here, more likely unknown, withheld, or missing

Similarly for _8 Dataset reference date_ the reason is likely to be unknown, withheld, or missing

For _Conformity explanation_  all nil reasons are in scope

**Comment by nmtoken** [comment] 2020-02-11 11:25
Also note the reported issue is primarily **not** about the nilreason but about the insertion of an empty element, where none existed previously.  As per the below example it's the insertion of the `<gco:CharacterString/>` that makes it invalid

    <gmd:parentIdentifier gco:nilReason="inapplicable"/> (valid) 
becomes invalid:

    <gmd:parentIdentifier xmlns:xs="http://www.w3.org/2001/XMLSchema"
                     xmlns:geonet="http://www.fao.org/geonetwork"
                     gco:nilReason="missing">
        <gco:CharacterString/>
    </gmd:parentIdentifier>

**Comment by archaeogeek** [comment] 2020-02-11 11:30
@nmtoken yes. For the elements listed above for which nilreasons are acceptable, that won't happen. For all the others then they will show as a text entry box that you will need to fill in. As discussed, this is a work in progress and I am talking to the developers about a more elegant way of dealing with this so it may be a moot point anyhow

**Comment by archaeogeek** [comment] 2020-02-13 09:02
@nmtoken something has been bothering me a bit about what you're reporting here and I've only figured it out after reviewing the code. The empty character strings that are inserted for elements with nilreasons should only be a temporary thing and should be removed when the record is saved, and I'm pretty sure before validation. Effectively they are place holders so that you can choose to edit the value if you so desire, but should be reverted if you don't do that. It sounds like what you're saying is that this is not happening?

So that I can try to replicate this issue- can you give me step by step instructions, particularly around how you're getting the record into the catalog, and then how you're validating it (and whether or not you press save at any point). Also, are you setting the metadata standard name and version to UK Gemini and 2.3 respectively? (Just to check it's actually validating against Gemini and not one of the other standards)

Thanks

Jo

**Comment by nmtoken** [comment] 2020-02-13 13:07
> It sounds like what you're saying is that this is not happening?

It doesn't look like it's happening.

Steps...

1. You imported the example data into your GeoNetwork

1. I exported the metadata from your GeoNetwork

1. I ran validation against the GEMINI 2.3 schematron in oXygen

I didn't do any editing in GeoNetwork, or any saving, but you may have.

**Comment by archaeogeek** [comment] 2020-02-13 16:04
OK, I'd assumed you were testing imports with a clean version of the file. 

Anyhow... the problem isn't in the implementation of Gemini per se, it's in the way Geonetwork handles ISO19139, which Gemini is deferring to. That's why I was confused! The ISO19139 plugin is responsible for changing the nilreason to missing when there's an empty characterstring element. This is by design, but we should be able to overwrite of that bit of processing in Gemini. Sorry for the faff and going down the wrong rabbit holes...

**Comment by nmtoken** [comment] 2020-02-13 16:15
> The ISO19139 plugin is responsible for changing the nilreason to missing when there's an empty characterstring element. 

So we haven't noticed this default behaviour before, because we don't do any editing in GeoNetwork.  We've always created the metadata elsewhere and imported it.  Then just used the GUI / CSW endpoint as appropriate.

**Comment by archaeogeek** [comment] 2020-02-13 16:20
That would explain it, but without digging through the commits I couldn't say how long it has been in place. Once this particular issue is resolved, the thing to check will be whether either of these processes are triggered by a straightforward import or harvest, or whether they are only triggered when the record is opened in the editor.

**Comment by archaeogeek** [comment] 2020-03-05 16:46
Closing this as I think we've done the work to fix. The process is that the character string element needs to be added for geonetwork to display the element in the editing interface, but any nilreason is kept. If the character string element is not filled in, then it is stripped out on save or validation, so we're back to where we were in the first place. 

Note that this has to be done on an element by element basis, so we've done the ones that the AGI guidance says can/should accept nilreasons. Others would need to be done on advice from the AGI working group.

**Closed as completed by archaeogeek** 2020-03-05 16:46 UTC
